# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Samuel/risc_arty/risc_arty.srcs/sources_1/ip/imem_bram/imem_bram.xci
# IP: The module: 'imem_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Samuel/risc_arty/risc_arty.gen/sources_1/ip/imem_bram/imem_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Samuel/risc_arty/risc_arty.srcs/sources_1/ip/imem_bram/imem_bram.xci
# IP: The module: 'imem_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Samuel/risc_arty/risc_arty.gen/sources_1/ip/imem_bram/imem_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
